#企业微信应用通知参数配置
#下方填入企业微信应用以及plex相关的参数,xxxxx就是需要自己填的，appcode按需修改
wxapp:
  corpid: ww77c295d145f28e9b
  secret: jBM8tQV0_I6A8-KfRpuoqEpVIqGpUUMWElgIzkFcK18
  agentid: 1000002
  touser: ChenYeWei
  type: news   #可选消息类型 news(图文消息) textcard(卡片消息，不展示影片海报图) text(纯文本)
  plex_server_url: http://plex.0bm.cn:32400     #外网 plex 服务器地址，能外网访问的域名地址。若填内网地址，推送图片只在内网才能查看到，外网时图片无法显示
  picurl_default: https://raw.githubusercontent.com/WadeChenn/Picgo/main/20220908183946.png   #通知缺省背景图，当没有获取到背景封面时调用此图
  plex_token: xNjbvCpt-P1898dyDACz     #plex身份认证，否则无法获取封面背景图，获取方式：在plex中随意点开一部影片封面右下角3个点，然后选择获取信息，再点弹窗左下角的查看xml会跳转链接,查看浏览器地址栏有X-Plex-Token字样
  #配置正确的appcode可展示客户端ip归属地。该值为空则不展示。appcode获取方法（显示归属地其实没什么用，保持为空即可。如果一定要用，下面是方法）：在阿里云市场购买的1元含2万5千次请求，或者试用用免费的 https://reurl.cc/W103r5 进入管理控制台，在已购买的服务中可以找到AppCode
  appcode: ''
tgapp:
  plex_server_url: http://plex.0bm.cn:32400     #外网 plex 服务器地址，能外网访问的域名地址。若填内网地址，推送图片只在内网才能查看到，外网时图片无法显示
  picurl_default: https://raw.githubusercontent.com/WadeChenn/Picgo/main/20220908183946.png   #通知缺省背景图，当没有获取到背景封面时调用此图
  plex_token: xNjbvCpt-P1898dyDACz     #plex身份认证，否则无法获取封面背景图，获取方式：在plex中随意点开一部影片封面右下角3个点，然后选择获取信息，再点弹窗左下角的查看xml会跳转链接,查看浏览器地址栏有X-Plex-Token字样
  #配置正确的appcode可展示客户端ip归属地。该值为空则不展示。appcode获取方法（显示归属地其实没什么用，保持为空即可。如果一定要用，下面是方法）：在阿里云市场购买的1元含2万5千次请求，或者试用用免费的 https://reurl.cc/W103r5 进入管理控制台，在已购买的服务中可以找到AppCode
  tgbot_token: "5629587845:AAEUqozM5MyiF2sx0nKZD6kwQX6NilPe1so"
  user_id: "1409331285"
  type: "photo"